---
# [jan17] provision ASM and deploy secpol in BIP
# Notes:
# - global vars r stored in e ./inventory/host_vars which is ref fr e hosts file
# - pass in lh1 (SDmDC) or lh2 (Ansible) on CLI
# - AWS credentials must be defined and populated (akey and skey) eg. in ansible-vault
# - BIP credentials must be defined likewise (bip_user and bip_pass)


- name: "provision ASM and deploy secpol"
  hosts: "{{ host }}"
  gather_facts: false
  connection: local

  environment:
    F5_SERVER: "{{ bip }}"
    F5_SERVER_PORT: 8443
    F5_USER: "{{ bip_user }}"
    F5_PASSWORD: "{{ bip_pass }}"
    F5_VALIDATE_CERTS: no

  tasks:
  - name: deploy secpol
    bigip_asm_policy:
      name: HZ-WAAP-ASM
      file: "{{ asmxml }}"
      active: yes

  - name: create l7 policy
    bigip_policy:
      name: hackazon_l7_policy
      state: present

  - name: add WAAP rule to hackazon_l7_policy
    bigip_policy_rule:
      name: activate_waap_rule
      policy: hackazon_l7_policy
      actions:
      - type: enable
        asm_policy: HZ-WAAP-ASM
      conditions:
      - type: all_traffic
      state: present

  - name: attach L7_policy to VS
    bigip_virtual_server:
      name: "{{ VSname }}"
      all_profiles:
      - tcp
      - http
      - websecurity
      all_policies:
      - hackazon_l7_policy

  - name: create security logging profile
    bigip_command:
      commands: 'create security log profile hz_log_profile application add { app { filter add { request-type { values add { illegal } } search-all {} } format { field-delimiter \"\#\" fields { ip_client geo_location ip_address_intelligence src_port dest_ip dest_port protocol method uri x_forwarded_for_header_value request_status support_id session_id username violations violation_rating attack_type query_string policy_name sig_ids sig_names sig_set_names severity request } } local-storage disabled logic-operation and remote-storage remote servers add { {{ elk_host }}:5000 {} } } }'
    ignore_errors: no

  - name: assign security logging profile to VS
    bigip_command:
      commands: 'modify ltm virtual {{ VSname }} security-log-profiles replace-all-with { hz_log_profile Log\ illegal\ requests }'


## auto-provisioned in CFT to speed up demo runtime
#  - name: provision ASM
#    bigip_provision:
#      module: asm
#      # state: absent
#      level: minimum   # sthg wrong w minimum/minimal!
#
#  - name: reboot BIP
#    bigip_command:
#      commands:
#      - save sys config
#      - reboot
#    ignore_errors: true
#
#  - name: Wait for reboot to complete
#    pause:
#      seconds: 180
