# [dec17] deploy single-NIC BIP on existing VPC, #s1
# notes:
# - global vars r stored in e ./inventory/host_vars which is ref fr e hosts file
# - eg. ansible-playbook SDmDC/SD-AWS_s1_BIPdeploy.yml --vault-id @.vault_pw -e @secure.yml -vvv -e "host=lh1"
# - vars: stack: vpc: subnet: sshkp: biplic:
# - static public and private IPs are defined in vars file. latter is primarily for Tower
# - tim9: 3.5min CFT status complete
#         8.5min can ssh on T2.large > 10.45min TMUI appears > 15-17min online
#         check /var/log/onboard.log for "info: [pid: 10907] [lib/util.js] Onboard finished."
# - prereqs:
#   - VPC setup with SDmDC prefix and public subnet where EC2s will be deployed
#   - AWS credentials must be defined and populated (akey and skey) eg. in ansible-vault
#

- name: "Launch AWS BIGIP #s1"
  hosts: "{{ host }}"
  gather_facts: false
  connection: local

  environment:
    AWS_ACCESS_KEY: "{{ akey }}"
    AWS_SECRET_KEY: "{{ skey }}"
    AWS_REGION: "ap-southeast-1"  # SG
    ###
    F5_SERVER: "{{ bip }}"
    F5_SERVER_PORT: 8443
    F5_USER: "{{ bip_user }}"
    F5_PASSWORD: "{{ bip_pass }}"
    F5_VALIDATE_CERTS: no

  tasks:
  - name: Launch BIG-IP CFT
    cloudformation:
      stack_name: "{{ stack }}"
      state: "present"
      disable_rollback: true
      template: "../templates/f5-MCAS-deploy-bip_v3a.template"
      template_parameters:
        Vpc: "{{ vpc }}"
        EIP: "{{ ebip }}"
        priIP: "{{ priIP }}"
        BipSG: "{{ bipsg }}"
        TowerSG: "{{ towersg }}"
        BastionSG: "{{ bastionsg }}"
        licenseKey1: "{{ biplic }}"  # put in new eval best lic
        sshKey: "{{ sshkp }}"
        bipPass: "{{ bippass }}"
        subnet1Az1: "{{ subnet }}"   # look to make this dynamic

  # change BIP pw (todo)
  #- expect:
  #  command: ssh -i <bigip_cert>.pem admin@<bigip_ip> modify auth password admin ; save sys config
  #  responses:
  #    (?i)password: "newPassword"
  #  echo: yes

#  - name: get facts
#    cloudformation_facts:
#      stack_name: "{{ stack }}"
#    register: bigip
#  - set_fact:
#      bip: "{{ bigip['ansible_facts']['cloudformation']['JT-ANST']['stack_outputs']['Bigip1ExternalInterfacePrivateIp']}}"
#    when: bip=="10.1.1.1"
